--------------------------------------------------------
--  DDL for Table BULLETIN
--------------------------------------------------------

  CREATE TABLE "BDM"."BULLETIN" 
   (	"POST_NO" NUMBER DEFAULT "BDM"."BULLETIN_SEQ"."NEXTVAL", 
	"TITLE" VARCHAR2(300 BYTE), 
	"CONTENTS" CLOB, 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"MOD_DT" DATE, 
	"READ_CNT" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"MOD_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BDM"."BULLETIN"."POST_NO" IS '게시순서';
   COMMENT ON COLUMN "BDM"."BULLETIN"."TITLE" IS '제목';
   COMMENT ON COLUMN "BDM"."BULLETIN"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "BDM"."BULLETIN"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "BDM"."BULLETIN"."MOD_DT" IS '수정일';
   COMMENT ON COLUMN "BDM"."BULLETIN"."READ_CNT" IS '조회수';
   COMMENT ON COLUMN "BDM"."BULLETIN"."ID" IS '아이디';
   COMMENT ON COLUMN "BDM"."BULLETIN"."MOD_ID" IS '수정자';
   COMMENT ON TABLE "BDM"."BULLETIN"  IS '자유게시판';
