--------------------------------------------------------
--  Constraints for Table BULLETIN_COMMENTS
--------------------------------------------------------

  ALTER TABLE "BDM"."BULLETIN_COMMENTS" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "BDM"."BULLETIN_COMMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BDM"."BULLETIN_COMMENTS" ADD CONSTRAINT "PK_COMMENTS" PRIMARY KEY ("REG_NO")
  USING INDEX "BDM"."PK_COMMENTS"  ENABLE;
  ALTER TABLE "BDM"."BULLETIN_COMMENTS" MODIFY ("POST_NO" NOT NULL ENABLE);
