--------------------------------------------------------
--  Ref Constraints for Table BULLETIN_COMMENTS
--------------------------------------------------------

  ALTER TABLE "BDM"."BULLETIN_COMMENTS" ADD CONSTRAINT "FK_BULLETIN_TO_COMMENTS" FOREIGN KEY ("POST_NO")
	  REFERENCES "BDM"."BULLETIN" ("POST_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BDM"."BULLETIN_COMMENTS" ADD CONSTRAINT "FK_USERS_TO_COMMENTS" FOREIGN KEY ("ID")
	  REFERENCES "BDM"."USERS" ("ID") ON DELETE CASCADE ENABLE;
