--------------------------------------------------------
--  DDL for Table CODE
--------------------------------------------------------

  CREATE TABLE "BDM"."CODE" 
   (	"CATEGORY" VARCHAR2(30 BYTE), 
	"DIVS" NUMBER(5,0), 
	"DIV_NAME" VARCHAR2(100 BYTE), 
	"SEQ" NUMBER(3,0), 
	"USE_YN" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BDM"."CODE"."CATEGORY" IS '항목';
   COMMENT ON COLUMN "BDM"."CODE"."DIVS" IS '구분';
   COMMENT ON COLUMN "BDM"."CODE"."DIV_NAME" IS '상세네임';
   COMMENT ON COLUMN "BDM"."CODE"."SEQ" IS '순번';
   COMMENT ON COLUMN "BDM"."CODE"."USE_YN" IS '사용여부';
   COMMENT ON TABLE "BDM"."CODE"  IS '코드';
