--------------------------------------------------------
--  DDL for Table EAT
--------------------------------------------------------

  CREATE TABLE "BDM"."EAT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"CODE" VARCHAR2(20 BYTE), 
	"DIVS" VARCHAR2(2 BYTE), 
	"AMOUNT" NUMBER(3,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BDM"."EAT"."ID" IS '아이디';
   COMMENT ON COLUMN "BDM"."EAT"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "BDM"."EAT"."CODE" IS '식품코드';
   COMMENT ON COLUMN "BDM"."EAT"."DIVS" IS '섭취구분';
   COMMENT ON COLUMN "BDM"."EAT"."AMOUNT" IS '섭취량';
   COMMENT ON TABLE "BDM"."EAT"  IS '섭취량';
