--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "BDM"."NOTICE" 
   (	"POST_NO" NUMBER DEFAULT "BDM"."NOTICE_SEQ"."NEXTVAL", 
	"TITLE" VARCHAR2(300 BYTE), 
	"CONTENTS" CLOB, 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"READ_CNT" NUMBER, 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BDM"."NOTICE"."POST_NO" IS '게시순서';
   COMMENT ON COLUMN "BDM"."NOTICE"."TITLE" IS '제목';
   COMMENT ON COLUMN "BDM"."NOTICE"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "BDM"."NOTICE"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "BDM"."NOTICE"."READ_CNT" IS '조회수';
   COMMENT ON COLUMN "BDM"."NOTICE"."ID" IS '아이디';
   COMMENT ON TABLE "BDM"."NOTICE"  IS '공지사항';
