--------------------------------------------------------
--  Constraints for Table NUTRIENT
--------------------------------------------------------

  ALTER TABLE "BDM"."NUTRIENT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "BDM"."NUTRIENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BDM"."NUTRIENT" MODIFY ("KCAL" NOT NULL ENABLE);
  ALTER TABLE "BDM"."NUTRIENT" MODIFY ("CARBOHYDRATE" NOT NULL ENABLE);
  ALTER TABLE "BDM"."NUTRIENT" MODIFY ("PROTEIN" NOT NULL ENABLE);
  ALTER TABLE "BDM"."NUTRIENT" MODIFY ("FAT" NOT NULL ENABLE);
  ALTER TABLE "BDM"."NUTRIENT" MODIFY ("SUGARS" NOT NULL ENABLE);
  ALTER TABLE "BDM"."NUTRIENT" ADD CONSTRAINT "PK_NUTRIENT" PRIMARY KEY ("CODE")
  USING INDEX "BDM"."PK_NUTRIENT"  ENABLE;
