--------------------------------------------------------
--  DDL for Table NUTRIENT
--------------------------------------------------------

  CREATE TABLE "BDM"."NUTRIENT" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(120 BYTE), 
	"KCAL" NUMBER(4,0), 
	"CARBOHYDRATE" NUMBER(8,4), 
	"PROTEIN" NUMBER(8,4), 
	"FAT" NUMBER(8,4), 
	"SUGARS" NUMBER(8,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BDM"."NUTRIENT"."CODE" IS '식품코드';
   COMMENT ON COLUMN "BDM"."NUTRIENT"."NAME" IS '식품명';
   COMMENT ON COLUMN "BDM"."NUTRIENT"."KCAL" IS '에너지';
   COMMENT ON COLUMN "BDM"."NUTRIENT"."CARBOHYDRATE" IS '탄수화물';
   COMMENT ON COLUMN "BDM"."NUTRIENT"."PROTEIN" IS '단백질';
   COMMENT ON COLUMN "BDM"."NUTRIENT"."FAT" IS '지방';
   COMMENT ON COLUMN "BDM"."NUTRIENT"."SUGARS" IS '당류';
   COMMENT ON TABLE "BDM"."NUTRIENT"  IS '영양소';
