--------------------------------------------------------
--  DDL for Table QA
--------------------------------------------------------

  CREATE TABLE "BDM"."QA" 
   (	"POST_NO" NUMBER DEFAULT "BDM"."QA_SEQ"."NEXTVAL", 
	"TITLE" VARCHAR2(300 BYTE), 
	"CONTENTS" CLOB, 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"ID" VARCHAR2(20 BYTE), 
	"DISCLOSURE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENTS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "BDM"."QA"."POST_NO" IS '게시순서';
   COMMENT ON COLUMN "BDM"."QA"."TITLE" IS '제목';
   COMMENT ON COLUMN "BDM"."QA"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "BDM"."QA"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "BDM"."QA"."ID" IS '아이디';
   COMMENT ON COLUMN "BDM"."QA"."DISCLOSURE" IS '공개 여부';
