--------------------------------------------------------
--  DDL for Table QA_COMMENTS
--------------------------------------------------------

  CREATE TABLE "BDM"."QA_COMMENTS" 
   (	"REG_NO" NUMBER DEFAULT "BDM"."QA_COMMENTS_SEQ"."NEXTVAL", 
	"CONTENTS" VARCHAR2(300 BYTE), 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"POST_NO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"MOD_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BDM"."QA_COMMENTS"."REG_NO" IS '등록순서';
   COMMENT ON COLUMN "BDM"."QA_COMMENTS"."CONTENTS" IS '내용';
   COMMENT ON COLUMN "BDM"."QA_COMMENTS"."REG_DT" IS '등록일';
   COMMENT ON COLUMN "BDM"."QA_COMMENTS"."POST_NO" IS '게시순서';
   COMMENT ON COLUMN "BDM"."QA_COMMENTS"."ID" IS '아이디';
   COMMENT ON COLUMN "BDM"."QA_COMMENTS"."MOD_ID" IS '수정자';
   COMMENT ON TABLE "BDM"."QA_COMMENTS"  IS '댓글';
