--------------------------------------------------------
--  DDL for Table SEARCHS
--------------------------------------------------------

  CREATE TABLE "BDM"."SEARCHS" 
   (	"GENDER" NUMBER(1,0) DEFAULT 0, 
	"BIRTH" NUMBER(6,0) DEFAULT 000000, 
	"WORDS" VARCHAR2(100 BYTE), 
	"SEARCH_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BDM"."SEARCHS"."GENDER" IS '성별';
   COMMENT ON COLUMN "BDM"."SEARCHS"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "BDM"."SEARCHS"."WORDS" IS '검색어';
   COMMENT ON COLUMN "BDM"."SEARCHS"."SEARCH_DT" IS '검색날짜';
   COMMENT ON TABLE "BDM"."SEARCHS"  IS '통합검색';
