--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "BDM"."USERS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NO" NUMBER(8,0) DEFAULT "BDM"."USERS_SEQ"."NEXTVAL", 
	"PW" VARCHAR2(64 BYTE), 
	"EMAIL" VARCHAR2(320 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"BIRTH" NUMBER(6,0), 
	"GENDER" NUMBER(1,0), 
	"HEIGHT" NUMBER(4,1), 
	"WEIGHT" NUMBER(4,1), 
	"REG_DT" DATE DEFAULT SYSDATE, 
	"USER_FILTER" NUMBER(1,0) DEFAULT 2, 
	"ACTIVITY" NUMBER(3,0), 
	"SALT" VARCHAR2(32 BYTE), 
	"BLOCK" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BDM"."USERS"."ID" IS '아이디';
   COMMENT ON COLUMN "BDM"."USERS"."NO" IS '유저번호';
   COMMENT ON COLUMN "BDM"."USERS"."PW" IS '비밀번호';
   COMMENT ON COLUMN "BDM"."USERS"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "BDM"."USERS"."NAME" IS '이름';
   COMMENT ON COLUMN "BDM"."USERS"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "BDM"."USERS"."GENDER" IS '성별';
   COMMENT ON COLUMN "BDM"."USERS"."HEIGHT" IS '키';
   COMMENT ON COLUMN "BDM"."USERS"."WEIGHT" IS '몸무게';
   COMMENT ON COLUMN "BDM"."USERS"."REG_DT" IS '등록일자';
   COMMENT ON COLUMN "BDM"."USERS"."USER_FILTER" IS '사용자구분';
   COMMENT ON COLUMN "BDM"."USERS"."ACTIVITY" IS '활동량';
   COMMENT ON COLUMN "BDM"."USERS"."SALT" IS '암호화';
   COMMENT ON COLUMN "BDM"."USERS"."BLOCK" IS '제재';
   COMMENT ON TABLE "BDM"."USERS"  IS '유저';
