--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "BDM"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" MODIFY ("HEIGHT" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "BDM"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("ID")
  USING INDEX "BDM"."PK_USERS"  ENABLE;
