--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-05-2024   
--------------------------------------------------------
@C:\Users\user\Desktop\1차프로젝트\BULLETIN_SEQ.sql
@C:\Users\user\Desktop\1차프로젝트\COMMENTS_SEQ.sql
@C:\Users\user\Desktop\1차프로젝트\NEWS_SEQ.sql
@C:\Users\user\Desktop\1차프로젝트\NOTICE_SEQ.sql
@C:\Users\user\Desktop\1차프로젝트\QA_COMMENTS_SEQ.sql
@C:\Users\user\Desktop\1차프로젝트\QA_SEQ.sql
@C:\Users\user\Desktop\1차프로젝트\USERS_SEQ.sql
@C:\Users\user\Desktop\1차프로젝트\BULLETIN.sql
@C:\Users\user\Desktop\1차프로젝트\BULLETIN_COMMENTS.sql
@C:\Users\user\Desktop\1차프로젝트\CODE.sql
@C:\Users\user\Desktop\1차프로젝트\EAT.sql
@C:\Users\user\Desktop\1차프로젝트\HEART.sql
@C:\Users\user\Desktop\1차프로젝트\IMAGE.sql
@C:\Users\user\Desktop\1차프로젝트\NEWS.sql
@C:\Users\user\Desktop\1차프로젝트\NOTICE.sql
@C:\Users\user\Desktop\1차프로젝트\NUTRIENT.sql
@C:\Users\user\Desktop\1차프로젝트\QA.sql
@C:\Users\user\Desktop\1차프로젝트\QA_COMMENTS.sql
@C:\Users\user\Desktop\1차프로젝트\SEARCHS.sql
@C:\Users\user\Desktop\1차프로젝트\USERS.sql
--@C:\Users\user\Desktop\1차프로젝트\BULLETIN_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\BULLETIN_COMMENTS_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\CODE_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\EAT_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\HEART_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\IMAGE_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\NEWS_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\NOTICE_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\NUTRIENT_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\QA_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\QA_COMMENTS_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\SEARCHS_DATA_TABLE.xlsx
--@C:\Users\user\Desktop\1차프로젝트\USERS_DATA_TABLE.xlsx
@C:\Users\user\Desktop\1차프로젝트\PK_BULLETIN.sql
@C:\Users\user\Desktop\1차프로젝트\PK_CODE.sql
@C:\Users\user\Desktop\1차프로젝트\PK_COMMENTS.sql
@C:\Users\user\Desktop\1차프로젝트\PK_EAT.sql
@C:\Users\user\Desktop\1차프로젝트\PK_HEART.sql
@C:\Users\user\Desktop\1차프로젝트\PK_IMAGE.sql
@C:\Users\user\Desktop\1차프로젝트\PK_NEWS.sql
@C:\Users\user\Desktop\1차프로젝트\PK_NOTICE.sql
@C:\Users\user\Desktop\1차프로젝트\PK_NUTRIENT.sql
@C:\Users\user\Desktop\1차프로젝트\PK_QA.sql
@C:\Users\user\Desktop\1차프로젝트\PK_QA_COMMENTS.sql
@C:\Users\user\Desktop\1차프로젝트\PK_USERS.sql
@C:\Users\user\Desktop\1차프로젝트\SYS_IL0000084322C00003__.sql
@C:\Users\user\Desktop\1차프로젝트\SYS_IL0000084327C00003__.sql
@C:\Users\user\Desktop\1차프로젝트\SYS_IL0000086343C00003__.sql
@C:\Users\user\Desktop\1차프로젝트\SYS_IL0000088170C00003__.sql
@C:\Users\user\Desktop\1차프로젝트\PK_BULLETIN_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_COMMENTS_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_CODE_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_EAT_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_HEART_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_IMAGE_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_NEWS_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_NOTICE_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_NUTRIENT_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_QA_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_QA_COMMENTS_1.sql
@C:\Users\user\Desktop\1차프로젝트\PK_USERS_1.sql
@C:\Users\user\Desktop\1차프로젝트\BULLETIN_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\BULLETIN_COMMENTS_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\CODE_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\EAT_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\HEART_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\IMAGE_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\NEWS_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\NOTICE_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\NUTRIENT_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\QA_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\QA_COMMENTS_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\SEARCHS_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\USERS_CONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\BULLETIN_REFCONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\BULLETIN_COMMENTS_REFCONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\EAT_REFCONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\HEART_REFCONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\NEWS_REFCONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\NOTICE_REFCONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\QA_REFCONSTRAINT.sql
@C:\Users\user\Desktop\1차프로젝트\QA_COMMENTS_REFCONSTRAINT.sql
